### ISSUE TITLE
Switch to API Key instead of Site ID

### ISSUE THREAD

**Issue by jbanyer** [NewyGuy/ChargeHQ#1]
Hi there!

The Charge HQ push API now uses an API Key instead of a Site ID to identify the user that is pushing the data in.

Please see https://chargehq.net/kb/push-api for details.

The Site ID method is now deprecated and will be removed in future.

Cheers,
Jay.

**Comment by NewyGuy** [comment]
Script updated to use API key instead of Site ID.
